### ISSUE TITLE
Astro image integration 

### ISSUE THREAD

**Issue by brahimABD98** [manuelernestog/astro-modern-personal-website#13]
Astro image integration has been out for a while now and it enables caching images ,serving responsive images  with different sizes 
It's still experimental  but I've already test it on my personal website and seems to be working fine 
[Astro images docs ref](https://docs.astro.build/en/guides/integrations-guide/image/#overview)

**Comment by manuelernestog** [comment]
Hi @brahimABD98. Yes I'm also using it in another web site and works really nice. It would be a nice thing to have here too. 👍️
