### ISSUE TITLE
Like buttons plugin

### ISSUE THREAD

**Issue by giuseppelt** [manuelernestog/astro-modern-personal-website#17]
Hi, I created an [astro plugin](https://www.feelback.dev) which allows to add *Like* buttons to blog posts.
Are you open to integrate it in your template? I can create a PR to setup the integration. It will be just a few line of code. I will make the integration _optional_, meaning that if the `setting_key` is missing (the user doesn't want to use the plugin), nothing is affected and will change.

In general, the plugin allows to receive any kind of feedback, but I think for a blogsite _likes_ are more appropriate. Nonetheless, it's very easy and customizable.

Let me know.
Thanks.

**Comment by manuelernestog** [comment]
Hi @giuseppelt thanks for writing. You have an interesting service there. Sadly, I'm trying to not integrate any SaaS on the template. Any way, thanks. 

Best Regards

**Comment by giuseppelt** [comment]
It's fine.
I'm looking for beta testers, just to smooth out rough edges, if you have 10min of your time, just to try [Feelback](https://www.feelback.dev) it will be much appreciated. I can help if any question. If you have no time, don't worry, I understand.
Thanks anyway.
