### ISSUE TITLE
Blog title as a page name

### ISSUE THREAD

**Issue by ThePresence** [manuelernestog/astro-modern-personal-website#6]
Hi

Can the title of a blog post be used as the page name on a website, such as mysite.com/blog/my-blog-title instead of mysite.com/blog/post1?

**Comment by manuelernestog** [comment]
Hi @ThePresence. Yes you can. The slug on the website will be the same as the file name. 

For example, in this blog post https://manuelernestog.github.io/blog/company-of-one/  the file is `company-of-one.md`
